# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 04:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smipleblog', '0008_auto_20160313_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.CharField(default='XXXXXXXXXXXXXXXXXX', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 3, 15, 4, 42, 1, 445780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 4, 42, 1, 444998, tzinfo=utc)),
        ),
    ]
