# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 05:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smipleblog', '0009_auto_20160315_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 3, 15, 5, 8, 49, 688037, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 5, 8, 49, 687204, tzinfo=utc)),
        ),
    ]
